sudo: required
services:
  - docker

before_install:
  - docker build -t pavanvora/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pavanvora/react-test npm test -- --coverage

after_success:
  - docker build -t pavanvora/multi-client ./client
  - docker build -t pavanvora/multi-nginx ./nginx
  - docker build -t pavanvora/multi-server ./server
  - docker build -t pavanvora/multi-worker ./worker 
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push pavanvora/multi-client
  - docker push pavanvora/multi-nginx
  - docker push pavanvora/multi-server
  - docker push pavanvora/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker-1
  env: MultiDocker1-env
  bucket_name: elasticbeanstalk-us-west-2-620858374284
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY